"""
explain_cell.py — write the COMPLETE working for one product x city cell.

The engine stores only final numbers (beta, contributions, verdicts). This tool
re-derives every one of them for a single cell and writes the full audit trail —
the actual weekly rows, the early/recent windows, the fitted coefficients, and
every arithmetic step from raw data to the bucket decision — into a markdown
file a human can check line by line.

Usage:
    python -X utf8 scripts/explain_cell.py 32385_1kg_Bangalore
    -> output/WORKING_32385_1kg_Bangalore.md

Faithful to scripts/analysis/discount_plan.py: the panel, the model and every
formula are IMPORTED from it (not re-implemented), so this cannot drift from
production logic. The only new code is the printing.
"""
import os, sys, glob
import numpy as np
import pandas as pd
import importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))

spec = importlib.util.spec_from_file_location(
    "dp", os.path.join(ROOT, "scripts", "analysis", "discount_plan.py"))
dp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(dp)


def fmt(x, nd=4):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "n/a"
    return f"{x:.{nd}f}"


def main(cell_id):
    run, fact = dp._latest_facttable()
    L = []
    w = L.append

    # ── panel ───────────────────────────────────────────────────────────────
    panel = dp.build_panel(fact)
    if cell_id not in set(panel["cell_id"]):
        raise SystemExit(f"cell '{cell_id}' not in panel")
    g = panel[panel["cell_id"] == cell_id].sort_values("week").reset_index(drop=True)
    cat = g["category"].iloc[0]
    title = g["title"].iloc[0]
    pid = g["product_id"].iloc[0]
    city = g["city"].iloc[0]

    # fit ONLY this category (identical result to the full run for this cell)
    sub_panel = panel[panel["category"] == cat].copy()
    models, formula = dp.fit_models(sub_panel)
    mm = models.get(cat, {"ok": False})

    w(f"# The complete working — `{cell_id}`")
    w(f"**Product ID:** {pid} · **{title}** · {city} · {cat}")
    w(f"**Run:** `{os.path.basename(run)}` · generated by `scripts/explain_cell.py` — "
      f"every number below is re-derived live from the run's fact_table with the "
      f"production functions imported from `discount_plan.py`.")
    w("")

    # ── 1. the weekly rows ─────────────────────────────────────────────────
    w("## 1 · The raw material — every weekly row the model sees")
    w("")
    w("Days are aggregated to weeks. `price` and `disc` are **volume-weighted** "
      "(a 500-unit day counts more than a 3-unit day); `osa`, `ad_sov`, `cat_share` are means.")
    w("")
    w("| # | week | units | price ₹ | disc % | OSA % | ad_SOV | org_SOV | RPI vs comp | cat_share |")
    w("|---|------|------:|--------:|-------:|------:|-------:|--------:|------------:|----------:|")
    for i, r in g.iterrows():
        w(f"| {i+1} | {pd.to_datetime(r['week']).date()} | {r['units']:.0f} | "
          f"{r['price']:.1f} | {r['disc']:.1f} | {r['osa']:.0f} | "
          f"{r['ad_sov']:.2f} | {r.get('org_sov', float('nan')):.2f} | "
          f"{r.get('rpi_w', float('nan')):.3f} | {r['cat_share']:.3f} |")
    w("")
    n_wk = len(g)
    w(f"**{n_wk} clean weeks** survived the pre-filters (festival/OOS/outlier/edge-week "
      f"rows were removed upstream, in stage 2).")
    w("")

    # ── 2. the windows ─────────────────────────────────────────────────────
    recent = g.tail(4)
    early = g.head(max(4, n_wk // 3))
    w("## 2 · The two windows every comparison uses")
    w("")
    w(f"- **EARLY** = first `max(4, {n_wk}//3)` = **first {len(early)} weeks** "
      f"({pd.to_datetime(early['week'].iloc[0]).date()} → {pd.to_datetime(early['week'].iloc[-1]).date()})")
    w(f"- **RECENT** = **last 4 weeks** "
      f"({pd.to_datetime(recent['week'].iloc[0]).date()} → {pd.to_datetime(recent['week'].iloc[-1]).date()})")
    w("")
    w("| window mean | units | disc % | OSA % | ad_SOV | org_SOV | RPI | cat_share |")
    w("|---|------:|-------:|------:|-------:|--------:|----:|----------:|")
    w(f"| EARLY  | {early['units'].mean():.1f} | {early['disc'].mean():.2f} | "
      f"{early['osa'].mean():.1f} | {early['ad_sov'].mean():.3f} | "
      f"{early['org_sov'].mean():.3f} | {early['rpi_w'].mean():.3f} | {early['cat_share'].mean():.4f} |")
    w(f"| RECENT | {recent['units'].mean():.1f} | {recent['disc'].mean():.2f} | "
      f"{recent['osa'].mean():.1f} | {recent['ad_sov'].mean():.3f} | "
      f"{recent['org_sov'].mean():.3f} | {recent['rpi_w'].mean():.3f} | {recent['cat_share'].mean():.4f} |")
    w("")

    cur_disc = float(np.average(recent["disc"], weights=recent["units"].clip(lower=1e-6)))
    cur_price = float(np.average(recent["price"], weights=recent["units"].clip(lower=1e-6)))
    cur_units = float(recent["units"].mean())
    mrp = float(g["mrp"].median())
    osa_mean = float(g["osa"].mean())
    w("**Current state** (RECENT window, volume-weighted where money is involved):")
    w("")
    w(f"- `cur_disc` = weighted avg of recent disc = **{cur_disc:.2f}%**")
    w(f"- `cur_price` = weighted avg of recent price = **₹{cur_price:.2f}**")
    w(f"- `cur_units_wk` = mean recent units = **{cur_units:.1f}/week**")
    w(f"- `mrp` = median MRP over all weeks = **₹{mrp:.0f}**")
    w(f"- `osa_mean` = mean OSA over ALL weeks = **{osa_mean:.1f}%**")
    w("")

    # trend + share
    e_u, r_u = early["units"].mean(), recent["units"].mean()
    tr_ratio = r_u / e_u if e_u > 0 else 1.0
    trend = "growing" if tr_ratio > 1.05 else ("declining" if tr_ratio < 0.95 else "flat")
    e_cs, r_cs = early["cat_share"].mean(), recent["cat_share"].mean()
    cs_drop = (e_cs - r_cs) / e_cs if e_cs > 0 else 0.0
    w(f"**Trend**: recent/early units = {r_u:.1f}/{e_u:.1f} = **{tr_ratio:.2f}×** → `{trend}` "
      f"(flat band is 0.95–1.05).")
    w(f"**Share change**: (early − recent)/early = ({e_cs:.4f} − {r_cs:.4f})/{e_cs:.4f} = "
      f"**{cs_drop:+.3f}** → " +
      ("**comp_pressure = True** (drop > 0.15)" if cs_drop > 0.15 else
       f"comp_pressure = False (needs drop > +0.15; negative = share GREW {1-cs_drop:.1f}×)"))
    w("")

    # ── 3. the category model ──────────────────────────────────────────────
    w("## 3 · The category model this cell borrows its coefficients from")
    w("")
    if not mm.get("ok"):
        w(f"⚠ Category `{cat}` did NOT produce a trusted model "
          f"(reason: {mm.get('reason','fit below R² floor')}). Every downstream test is "
          f"skipped and the cell falls to Low confidence / monitor.")
    else:
        w(f"One Huber-robust regression fitted on the whole **{cat}** category "
          f"({mm['n_rows']} weekly rows across {mm['n_cells']} cells):")
        w("")
        w("```")
        w(formula)
        w("```")
        w("")
        w("| coefficient | value | plain meaning (per 1-unit change, log-units of sales) |")
        w("|---|------:|---|")
        w(f"| `disc` (β) | {mm['beta_disc']:+.5f} | one more discount point → {mm['beta_disc']*100:+.2f}% units (near d=0) |")
        w(f"| `disc²` (β₂) | {mm['beta_disc2']:+.7f} | curvature — the response bends with depth |")
        w(f"| `log_osa` | {mm['beta_osa']:+.4f} | 1% better availability → {mm['beta_osa']:+.3f}% units |")
        w(f"| `log_adsov` | {mm['beta_adsov']:+.4f} | paid ad visibility effect |")
        w(f"| `log_orgsov` | {mm['beta_orgsov']:+.4f} | organic search visibility effect |")
        w(f"| `rpi_w` | {mm['beta_comp']:+.4f} | competitor relative price — our price ÷ competitor's (MODEL v2: replaced own share, which was outcome-derived) |")
        w(f"| se(β) | {mm['se_disc']:.5f} | the uncertainty around β |")
        w(f"| R² (full) | {mm['r2_full']:.3f} | must clear the 0.60 floor → "
          f"{'PASSES' if mm['r2_full']>=0.60 else 'FAILS'} |")
        w("")
        w("*(β and β₂ are shared by every cell in the category — one cell's 26 noisy weeks "
          "can't estimate its own curve; 100+ cells together can. Each cell still has its own "
          "baseline via the `C(cell_id)` fixed effect.)*")
    w("")

    if not mm.get("ok"):
        text = "\n".join(L)
        _write(cell_id, text)
        return

    beta, beta2, se = mm["beta_disc"], mm["beta_disc2"], mm["se_disc"]

    # ── 4. contributions ───────────────────────────────────────────────────
    w("## 4 · The attribution — WHO gets credit for the growth (full arithmetic)")
    w("")
    w("**Principle:** contribution = (how much the factor MOVED between the windows) × "
      "(how much a move MATTERS, per the fitted coefficient). A factor that didn't move "
      "cannot explain growth, no matter how large its coefficient.")
    w("")
    d_r, d_e = recent["disc"].mean(), early["disc"].mean()
    c_disc = (beta*d_r + beta2*d_r*d_r) - (beta*d_e + beta2*d_e*d_e)
    w(f"**Discount** — uses the fitted curve value at each window's mean depth:")
    w("```")
    w(f"at RECENT depth {d_r:.2f}%:  β·d + β₂·d² = {beta:+.5f}·{d_r:.2f} + {beta2:+.7f}·{d_r:.2f}²")
    w(f"                            = {beta*d_r:+.5f} + {beta2*d_r*d_r:+.5f} = {beta*d_r+beta2*d_r*d_r:+.5f}")
    w(f"at EARLY  depth {d_e:.2f}%:  = {beta*d_e:+.5f} + {beta2*d_e*d_e:+.5f} = {beta*d_e+beta2*d_e*d_e:+.5f}")
    w(f"c_disc = {beta*d_r+beta2*d_r*d_r:+.5f} − ({beta*d_e+beta2*d_e*d_e:+.5f}) = {c_disc:+.5f}")
    w("```")
    w(f"→ the discount moved {d_e:.1f}% → {d_r:.1f}% between the windows "
      f"({d_r-d_e:+.1f}pp). {'A nearly-unmoved lever explains nothing.' if abs(d_r-d_e)<2 else ''}")
    w("")

    o_r, o_e = recent["osa"].mean(), early["osa"].mean()
    c_osa = mm["beta_osa"] * (np.log(max(o_r,1)) - np.log(max(o_e,1)))
    w(f"**Availability (OSA)** — coefficient × change in log(OSA):")
    w("```")
    w(f"c_osa = {mm['beta_osa']:+.4f} × (ln({o_r:.1f}) − ln({o_e:.1f}))")
    w(f"      = {mm['beta_osa']:+.4f} × ({np.log(max(o_r,1)):.4f} − {np.log(max(o_e,1)):.4f})")
    w(f"      = {mm['beta_osa']:+.4f} × {np.log(max(o_r,1))-np.log(max(o_e,1)):+.4f} = {c_osa:+.5f}")
    w("```")
    w("")

    a_r, a_e = recent["ad_sov"].mean(), early["ad_sov"].mean()
    c_ad = mm["beta_adsov"] * (np.log1p(a_r) - np.log1p(a_e))
    w(f"**Ad share-of-voice** — coefficient × change in log(1+SOV):")
    w("```")
    w(f"c_adsov = {mm['beta_adsov']:+.4f} × (ln(1+{a_r:.3f}) − ln(1+{a_e:.3f}))")
    w(f"        = {mm['beta_adsov']:+.4f} × ({np.log1p(a_r):.4f} − {np.log1p(a_e):.4f}) = {c_ad:+.5f}")
    w("```")
    w("")

    g_r, g_e = recent["org_sov"].mean(), early["org_sov"].mean()
    c_org = mm["beta_orgsov"] * (np.log1p(g_r) - np.log1p(g_e))
    w(f"**Organic search visibility** — coefficient × change in log(1+organic SOV):")
    w("```")
    w(f"c_orgsov = {mm['beta_orgsov']:+.4f} × (ln(1+{g_r:.3f}) − ln(1+{g_e:.3f}))")
    w(f"         = {mm['beta_orgsov']:+.4f} × ({np.log1p(g_r):.4f} − {np.log1p(g_e):.4f}) = {c_org:+.5f}")
    w("```")
    w("")
    r_r, r_e = recent["rpi_w"].mean(), early["rpi_w"].mean()
    c_comp = mm["beta_comp"] * (r_r - r_e)
    w(f"**Competitor relative price (RPI)** — coefficient × change in the price ratio "
      f"(MODEL v2: this replaced own category share, which was outcome-derived and circular):")
    w("```")
    w(f"c_comp = {mm['beta_comp']:+.4f} × (RPI_recent {r_r:.3f} − RPI_early {r_e:.3f})")
    w(f"       = {mm['beta_comp']:+.4f} × ({r_r - r_e:+.3f}) = {c_comp:+.5f}")
    w("```")
    w("")
    contrib = {"discount": c_disc, "osa": c_osa, "ad_sov": c_ad,
               "organic_sov": c_org, "competitive": c_comp}
    top = max(contrib, key=lambda k: abs(contrib[k]))
    driver = top if abs(contrib[top]) >= 0.05 else "steady"
    w("**Scoreboard** (log-units; ±0.05 is the materiality bar `MATERIAL_CONTRIB`):")
    w("")
    w("| factor | contribution | material? |")
    w("|---|------:|---|")
    for k, v in contrib.items():
        w(f"| {k} | {v:+.4f} | {'YES' if abs(v)>=0.05 else 'no (below 0.05)'} |")
    w("")
    w(f"→ **driver = `{driver}`**. For scale: the cell's actual log-unit growth "
      f"(recent vs early) is ln({r_u:.0f}/{e_u:.0f}) = {np.log(r_u/e_u):+.3f}. "
      f"Compare each contribution against that total.")
    w("")
    w("*Honest caveat: this is a first-order decomposition using window means — a fair "
      "share-out, not a proof. The rigorous causal statement about the discount comes from "
      "the CI test below, not from this table.*")
    w("")

    # ── 5. the break-even test ─────────────────────────────────────────────
    w("## 5 · The break-even test — the verdict arithmetic")
    w("")
    be_beta = 1.0 / max(100.0 - cur_disc, 1.0)
    marg_beta = beta + 2.0 * beta2 * cur_disc
    hi = marg_beta + 1.96 * se
    lo = marg_beta - 1.96 * se
    w(f"**Pay-line** (what one more discount point must earn at today's depth):")
    w("```")
    w(f"be_beta = 1/(100 − {cur_disc:.2f}) = 1/{100-cur_disc:.2f} = {be_beta:.5f}")
    w("```")
    w(f"**Marginal response** (what one more point actually buys at today's depth):")
    w("```")
    w(f"marg_beta = β + 2·β₂·d = {beta:+.5f} + 2·({beta2:+.7f})·{cur_disc:.2f}")
    w(f"          = {beta:+.5f} + ({2*beta2*cur_disc:+.5f}) = {marg_beta:+.5f}")
    w("```")
    w(f"**The 95% confidence interval** around the marginal response:")
    w("```")
    w(f"CI = marg_beta ± 1.96·se = {marg_beta:+.5f} ± 1.96·{se:.5f}")
    w(f"   = [{lo:+.5f} , {hi:+.5f}]")
    w("```")
    w(f"**The two one-sided tests:**")
    w("```")
    w(f"reliably_waste:  optimistic edge {hi:+.5f}  <  pay-line {be_beta:.5f} ?  "
      f"{'YES → WASTE PROVEN' if hi < be_beta else 'no'}")
    w(f"reliably_pays :  pessimistic edge {lo:+.5f}  >  pay-line {be_beta:.5f} ?  "
      f"{'YES → PAYS PROVEN' if lo > be_beta else 'no'}")
    w("```")
    verdict = ("WASTE — even the optimistic reading can't pay" if hi < be_beta else
               ("PAYS — even the pessimistic reading clears the bar" if lo > be_beta else
                "UNCERTAIN — the interval straddles the pay-line → monitor"))
    w(f"→ **{verdict}**")
    w("")

    # ── 6. target discount ─────────────────────────────────────────────────
    w("## 6 · The target — where the discount should sit")
    w("")
    grid = np.arange(0.0, 60.5, 0.5)
    nr = (1.0 - grid/100.0) * dp._units_factor(grid, beta, beta2)
    be_disc = float(grid[int(np.argmax(nr))])
    floor = float(sub_panel.groupby("category")["disc"].quantile(0.10)[cat])
    tgt = min(cur_disc, max(be_disc, floor))
    w("Net-revenue curve NR(d) ∝ (1 − d/100)·exp(β·d + β₂·d²), grid-searched 0→60% "
      "in 0.5 steps. The best few points:")
    w("")
    order = np.argsort(nr)[::-1][:5]
    w("| discount d | relative net revenue |")
    w("|---:|---:|")
    for i in sorted(order):
        w(f"| {grid[i]:.1f}% | {nr[i]:.4f} |")
    w("")
    w("```")
    w(f"be_disc (revenue-optimal) = {be_disc:.1f}%")
    w(f"floor (category's 10th-pct observed discount — never price below evidence) = {floor:.2f}%")
    w(f"tgt_disc = min(cur {cur_disc:.2f}, max(be {be_disc:.1f}, floor {floor:.2f})) = {tgt:.2f}%")
    w("```")
    w("")

    # ── 7. the money ───────────────────────────────────────────────────────
    w("## 7 · The money — units, revenue, spend at the target")
    w("")
    tgt_price = mrp * (1 - tgt/100.0)
    uf_c = dp._units_factor(cur_disc, beta, beta2)
    uf_t = dp._units_factor(tgt, beta, beta2)
    ratio = min(uf_t / max(uf_c, 1e-9), 1.0)
    tgt_units = cur_units * ratio
    w("```")
    w(f"units_factor(d) = exp(β·d + β₂·d²)")
    w(f"  at cur {cur_disc:.2f}%: exp({beta:+.5f}·{cur_disc:.2f} + {beta2:+.7f}·{cur_disc:.2f}²) = {uf_c:.4f}")
    w(f"  at tgt {tgt:.2f}%: = {uf_t:.4f}")
    w(f"ratio = {uf_t:.4f}/{uf_c:.4f} = {uf_t/uf_c:.4f} → clamped to ≤1 → {ratio:.4f}")
    w(f"tgt_units = {cur_units:.1f} × {ratio:.4f} = {tgt_units:.1f}/week  "
      f"({(ratio-1)*100:+.1f}% volume)")
    w("```")
    cur_nr = cur_units * cur_price
    tgt_nr = tgt_units * tgt_price
    gain_wk = tgt_nr - cur_nr
    w("```")
    w(f"revenue now    = {cur_units:.1f} × ₹{cur_price:.2f} = ₹{cur_nr:,.0f}/week")
    w(f"revenue at tgt = {tgt_units:.1f} × ₹{tgt_price:.2f} = ₹{tgt_nr:,.0f}/week")
    w(f"net gain       = ₹{gain_wk:,.0f}/week × 30/7 = ₹{gain_wk*30/7:,.0f}/month")
    w("```")
    spend_c = cur_units * mrp * cur_disc/100.0
    spend_t = tgt_units * mrp * tgt/100.0
    w("```")
    w(f"discount spend now    = {cur_units:.1f} × ₹{mrp:.0f} × {cur_disc:.2f}% = ₹{spend_c:,.0f}/week (₹{spend_c*30/7:,.0f}/mo)")
    w(f"discount spend at tgt = {tgt_units:.1f} × ₹{mrp:.0f} × {tgt:.2f}% = ₹{spend_t:,.0f}/week (₹{spend_t*30/7:,.0f}/mo)")
    w(f"spend RETURNED        = ₹{(spend_c-spend_t)*30/7:,.0f}/month")
    w("```")
    w("")

    # ── 8. the gates ───────────────────────────────────────────────────────
    w("## 8 · The gates — walked in firing order")
    w("")
    checks = [
        ("Gate 1a — OSA level", f"osa_mean {osa_mean:.1f}% < 75?", osa_mean < 75),
        ("Gate 1b — OSA drag", f"c_osa {c_osa:+.4f} < −0.05?", c_osa < -0.05),
        ("Gate 2a — share collapse", f"cs_drop {cs_drop:+.3f} > +0.15?", cs_drop > 0.15),
        ("Gate 2b — comp drag", f"c_comp {c_comp:+.4f} < −0.05?", c_comp < -0.05),
        ("Gate 3 — SOV drag", f"c_adsov {c_ad:+.4f} < −0.05?", c_ad < -0.05),
    ]
    bucket = None
    for name, cond, fired in checks:
        w(f"- **{name}**: {cond} → {'**FIRES**' if fired else 'no'}")
        if fired and bucket is None:
            bucket = {"Gate 1a — OSA level": "a_stock", "Gate 1b — OSA drag": "a_stock",
                      "Gate 2a — share collapse": "b_competitive",
                      "Gate 2b — comp drag": "b_competitive",
                      "Gate 3 — SOV drag": "f_monitor"}[name]
    if bucket is None:
        has_room = cur_disc > tgt + 0.5
        waste_ok = (hi < be_beta) and has_room and (gain_wk*30/7 > 0)
        w(f"- **Gate 4 — waste cut**: reliably_waste {'True' if hi<be_beta else 'False'} "
          f"AND has_room ({cur_disc:.1f} > {tgt:.1f}+0.5 = {has_room}) "
          f"AND net_gain>0 ({gain_wk*30/7:,.0f}) → {'**FIRES → c_waste_cut**' if waste_ok else 'no'}")
        if waste_ok:
            bucket = "c_waste_cut"
        else:
            pays_ok = (lo > be_beta) and (cur_disc < be_disc)
            w(f"- **Gate 5 — reinvest**: reliably_pays {'True' if lo>be_beta else 'False'} "
            f"AND cur {cur_disc:.1f} < be_disc {be_disc:.1f} → "
            f"{'**FIRES → e_reinvest**' if pays_ok else 'no'}")
            bucket = "e_reinvest" if pays_ok else "f_monitor"
    w("")
    w(f"### → FINAL BUCKET: **`{bucket}`**")
    w("")

    # confidence
    disc_std = float(g["disc"].std())
    conf = ("High" if (mm.get("ok") and n_wk >= 8 and disc_std >= 1.5) else
            ("Experimental" if mm.get("ok") else "Low"))
    w(f"**Confidence**: cat_ok={mm.get('ok')} AND n_weeks {n_wk}≥8 AND "
      f"disc_std {disc_std:.2f}≥1.5 → **{conf}**")
    w("")
    w("---")
    w("*Cross-check: compare every number above against "
      f"`output/runs/{os.path.basename(run)}/plan/all_cells.csv` row `{cell_id}`. "
      "Tiny rounding differences (last decimal) are display-only.*")

    _write(cell_id, "\n".join(L))


def _write(cell_id, text):
    dest = os.path.join(ROOT, "output", f"WORKING_{cell_id}.md")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w", encoding="utf-8") as f:
        f.write(text)
    print("WROTE:", dest)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "32385_1kg_Bangalore")
